export default [
    { name: "Ageur", imageName: "ageur.webp", token: "agEUR" },
    { name: "ApxETH", imageName: "apxeth.webp", token: "apxETH" },
    { name: "Atom", imageName: "atom.webp", token: "ATOM" },
    { name: "BNB", imageName: "bnb.webp", token: "BNB" },
    { name: "Brazilian Real", imageName: "brl.webp", token: "BRL" },
    { name: "BsdETH", imageName: "bsdeth.webp", token: "bsdETH" },
    { name: "Bitcoin", imageName: "btc.webp", token: "BTC" },
    { name: "Canto", imageName: "canto.webp", token: "CANTO" },
    { name: "Celo", imageName: "celo.webp", token: "CELO" },
    { name: "cNote", imageName: "cnote.webp", token: "cNOTE" },
    { name: "Curve DAO Token", imageName: "crv.webp", token: "CRV" },
    { name: "Ethereum", imageName: "eth.webp", token: "ETH" },
    { name: "ETHx", imageName: "ethx.webp", token: "ETHx" },
    { name: "Euro", imageName: "eur.png", token: "EUR" },
    { name: "eUSD", imageName: "eusd.webp", token: "eUSD" },
    { name: "ezETH", imageName: "ezeth.webp", token: "ezETH" },
    { name: "Frax", imageName: "frax.webp", token: "FRAX" },
    { name: "Frax Share", imageName: "fxs.webp", token: "FXS" },
    { name: "British Pound", imageName: "gbp.webp", token: "GBP" },
    { name: "Manta", imageName: "manta.webp", token: "MANTA" },
    { name: "Merlin", imageName: "merl.webp", token: "MERL" },
    { name: "Mantle", imageName: "mnt.webp", token: "MNT" },
    { name: "Mode", imageName: "mode.webp", token: "MODE" },
    { name: "Origin Sharded Ether", imageName: "oseth.webp", token: "osETH" },
    { name: "Premia", imageName: "premia.webp", token: "PREMIA" },
    { name: "pufETH", imageName: "pufeth.webp", token: "pufETH" },
    { name: "Rocket Pool ETH", imageName: "rseth.webp", token: "rsETH" },
    { name: "Rocket Pool Wrapped Staked ETH", imageName: "rsweth.webp", token: "rswETH" },
    { name: "Staked Frax Ether", imageName: "sfrxeth.webp", token: "sfrxETH" },
    { name: "SolvBTC", imageName: "solvbtc.webp", token: "SolvBTC_MERLIN" },
    { name: "Lido Staked Ether", imageName: "steth.webp", token: "stETH" },
    { name: "Stone", imageName: "stone.webp", token: "STONE" },
    { name: "Staked USDe", imageName: "susde.webp", token: "sUSDe" },
    { name: "Celestia", imageName: "tia.webp", token: "TIA" },
    { name: "TRON", imageName: "trx.webp", token: "TRX" },
    { name: "USD+", imageName: "usd+.webp", token: "USD+" },
    { name: "USD Base", imageName: "usdb.webp", token: "USDB" },
    { name: "USD Coin", imageName: "usdc.webp", token: "USDC" },
    { name: "USDe", imageName: "usde.webp", token: "USDe" },
    { name: "Tether", imageName: "usdt.webp", token: "USDT" },
    { name: "Wrapped Ether", imageName: "weeth.webp", token: "weETH" },
    { name: "Wrapped Staked Ether", imageName: "wsteth.webp", token: "wstETH" },
    { name: "Wrapped USDM", imageName: "wusdm.webp", token: "wUSDM" },
    { name: "Gold", imageName: "xaut.webp", token: "XAU" },
    { name: "Tezos", imageName: "xtz.webp", token: "XTZ" },
    { name: "Venus", imageName: "xvs.webp", token: "XVS" },
    { name: "ZK", imageName: "zk.webp", token: "ZK" },
    { name: "placeholder", imageName: "placeholder.png", token: "placeholder" }
];